name: VSCode Extension CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Package
        run: yarn package

      - name: Run tests in headless mode
        run: xvfb-run --auto-servernum --server-num=1 yarn run vscode-test
